### ISSUE TITLE
Please add 64-bit architecture libs

### ISSUE THREAD

**Issue by kasim1011** [wysaid/android-gpuimage-plus-libs#2]
Hello @wysaid 

I hope you're doing well, As of Google Play requires 64-bit architecture support, Please share the 64-bit libs.

Thanks

**Comment by wysaid** [comment]
Hello,  64-bit libs are already provided.
Do you see the [https://github.com/wysaid/android-gpuimage-plus-libs/tree/master/arm64-v8a](https://github.com/wysaid/android-gpuimage-plus-libs/tree/master/arm64-v8a)

Or: http://jcenter.bintray.com/org/wysaid/gpuimage-plus/2.6.1/
